/* consolidated mariadb schema */ 

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `Pucks` (
  `position` varchar(1) NOT NULL DEFAULT '',
  `type` varchar(10) NOT NULL,
  `name` varchar(20) DEFAULT NULL,
  `owner` varchar(30) DEFAULT NULL,
  PRIMARY KEY (`position`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_swedish_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `dataset_runs` (
  `data_id` int(11) NOT NULL AUTO_INCREMENT,
  `username` varchar(255) DEFAULT NULL,
  `run_prefix` varchar(255) NOT NULL,
  `master_files` MEDIUMTEXT DEFAULT NULL,
  `total_frames` int(11) DEFAULT NULL,
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  `collect_type` varchar(255) DEFAULT NULL,
  `headers` MEDIUMTEXT DEFAULT NULL,
  `mounted` varchar(255) DEFAULT NULL,
  `meta_user` text DEFAULT NULL,
  PRIMARY KEY (`data_id`),
  UNIQUE KEY `uq_run_prefix_created_at` (`run_prefix`,`created_at`),
  KEY `ix_dataset_runs_run_prefix` (`run_prefix`)
) ENGINE=InnoDB AUTO_INCREMENT=3253 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `pipelinestatus` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `command` varchar(1024) NOT NULL,
  `state` varchar(20) NOT NULL,
  `pipeline` varchar(20) NOT NULL,
  `imagedir` varchar(255) NOT NULL,
  `workdir` varchar(255) NOT NULL,
  `log` text NOT NULL,
  `warning` text NOT NULL,
  `processing_id` int(11) NOT NULL,
  `hostname` varchar(255) NOT NULL,
  `sampleName` varchar(255) NOT NULL,
  `sampleNumber` int(11) NOT NULL,
  `username` varchar(20) NOT NULL,
  `beamline` varchar(255) NOT NULL,
  `starttime` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `elapsedtime` varchar(255) NOT NULL,
  `imageSet` varchar(255) NOT NULL,
  `logfile` varchar(1024) NOT NULL,
  `delete` int(11) NOT NULL,
  `pi_id` int(12) DEFAULT NULL,
  `esaf_id` int(12) DEFAULT NULL,
  `primary_group` varchar(30) DEFAULT NULL,
  `datasets` text DEFAULT NULL,
  `dataset_run_id` int(11) DEFAULT NULL,
  `run_prefix` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `pipelinestatus_pipeline` (`pipeline`),
  KEY `pipelinestatus_username` (`username`),
  KEY `pipelinestatus_dataset_run_id` (`dataset_run_id`),
  CONSTRAINT `pipelinestatus_dataset_run_id_ibfk` FOREIGN KEY (`dataset_run_id`) REFERENCES `dataset_runs` (`data_id`) ON DELETE SET NULL
) ENGINE=InnoDB AUTO_INCREMENT=65124 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `dataprocessresults` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `sampleNumber` int(11) NOT NULL,
  `sampleName` varchar(255) NOT NULL,
  `imageSet` varchar(255) NOT NULL,
  `state` varchar(255) NOT NULL,
  `software` varchar(255) NOT NULL,
  `scalingsoftware` varchar(255) NOT NULL,
  `collectType` varchar(255) NOT NULL,
  `overlap` int(11) NOT NULL,
  `inverseOn` int(11) NOT NULL,
  `firstFrame` varchar(255) NOT NULL,
  `workdir` varchar(255) NOT NULL,
  `subdir` varchar(255) NOT NULL,
  `imagedir` varchar(255) NOT NULL,
  `images` varchar(255) NOT NULL,
  `unitcell` varchar(255) NOT NULL,
  `lowresolution` varchar(255) NOT NULL,
  `lowresolution_inner` varchar(255) NOT NULL,
  `lowresolution_outer` varchar(255) NOT NULL,
  `highresolution` varchar(255) NOT NULL,
  `highresolution_inner` varchar(255) NOT NULL,
  `highresolution_outer` varchar(255) NOT NULL,
  `rmerge` varchar(255) NOT NULL,
  `rmerge_inner` varchar(255) NOT NULL,
  `rmerge_outer` varchar(255) NOT NULL,
  `rpim` varchar(255) NOT NULL,
  `rpim_inner` varchar(255) NOT NULL,
  `rpim_outer` varchar(255) NOT NULL,
  `cchalf` varchar(255) NOT NULL,
  `cchalf_inner` varchar(255) NOT NULL,
  `cchalf_outer` varchar(255) NOT NULL,
  `completeness` varchar(255) NOT NULL,
  `completeness_inner` varchar(255) NOT NULL,
  `completeness_outer` varchar(255) NOT NULL,
  `anom_completeness` varchar(255) NOT NULL,
  `anom_completeness_inner` varchar(255) NOT NULL,
  `anom_completeness_outer` varchar(255) NOT NULL,
  `multiplicity` varchar(255) NOT NULL,
  `multiplicity_inner` varchar(255) NOT NULL,
  `multiplicity_outer` varchar(255) NOT NULL,
  `anom_multiplicity` varchar(255) NOT NULL,
  `anom_multiplicity_inner` varchar(255) NOT NULL,
  `anom_multiplicity_outer` varchar(255) NOT NULL,
  `isigmai` varchar(255) NOT NULL,
  `isigmai_inner` varchar(255) NOT NULL,
  `isigmai_outer` varchar(255) NOT NULL,
  `spacegroup` varchar(255) NOT NULL,
  `truncate_log` varchar(255) NOT NULL,
  `truncate_mtz` varchar(255) NOT NULL,
  `run_stats` text DEFAULT NULL,
  `log` varchar(255) NOT NULL,
  `warning` text NOT NULL,
  `timestamp` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `scale_log` varchar(255) NOT NULL,
  `start` varchar(255) NOT NULL,
  `end` varchar(255) NOT NULL,
  `prefix` varchar(255) NOT NULL,
  `isa` varchar(255) NOT NULL,
  `rmeas` varchar(255) NOT NULL,
  `rmeas_inner` varchar(255) NOT NULL,
  `rmeas_outer` varchar(255) NOT NULL,
  `pipeline` varchar(255) NOT NULL,
  `wavelength` varchar(255) NOT NULL,
  `nobs` varchar(255) NOT NULL,
  `nuniq` varchar(255) NOT NULL,
  `table1` text NOT NULL,
  `report_url` varchar(1024) NOT NULL,
  `pipelinestatus_id` int(11) NOT NULL,
  `reprocess` int(11) NOT NULL,
  `solve` varchar(255) NOT NULL,
  `spacegroup_choices` text NOT NULL,
  PRIMARY KEY (`id`),
  KEY `dataprocessresults_pipelinestatus_id` (`pipelinestatus_id`),
  CONSTRAINT `dataprocessresults_ibfk_1` FOREIGN KEY (`pipelinestatus_id`) REFERENCES `pipelinestatus` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=23806 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `screenstrategyresults` (
  `sampleNumber` int(11) NOT NULL AUTO_INCREMENT,
  `sampleName` varchar(512) NOT NULL,
  `directory` varchar(250) NOT NULL,
  `images` varchar(250) NOT NULL,
  `software` varchar(255) NOT NULL,
  `state` varchar(255) NOT NULL,
  `workdir` varchar(512) NOT NULL,
  `index_table` text NOT NULL,
  `unitcell` varchar(100) NOT NULL,
  `bravais_lattice` varchar(10) NOT NULL,
  `rmsd` varchar(50) NOT NULL,
  `ice_rings` varchar(50) NOT NULL,
  `resolution_from_spots` varchar(30) NOT NULL,
  `n_spots` varchar(30) NOT NULL,
  `n_spots_ice` varchar(30) NOT NULL DEFAULT '0',
  `n_ice_rings` varchar(30) NOT NULL DEFAULT '0',
  `avg_spotsize` varchar(20) NOT NULL,
  `spacegroup` varchar(30) NOT NULL,
  `solution_number` varchar(30) NOT NULL,
  `penalty` varchar(30) NOT NULL,
  `mosaicity` varchar(50) NOT NULL,
  `score` varchar(30) NOT NULL,
  `resolution_from_integ` varchar(30) NOT NULL,
  `warning` text NOT NULL,
  `anomalous` smallint(6) NOT NULL,
  `osc_start` varchar(30) NOT NULL,
  `osc_end` varchar(30) NOT NULL,
  `osc_delta` varchar(30) NOT NULL,
  `completeness_native` varchar(30) NOT NULL,
  `completeness_anomalous` varchar(30) NOT NULL,
  `completeness_referencedata` varchar(30) NOT NULL,
  `detectorwarning` varchar(512) NOT NULL,
  `detectordistance` varchar(30) NOT NULL,
  `referencedata` varchar(512) NOT NULL,
  `displaytext` varchar(250) NOT NULL,
  `xplanlog` text NOT NULL,
  `strategy` text NOT NULL,
  `pipelinestatus_id` int(11) NOT NULL,
  `reprocess` int(11) NOT NULL,
  `solvent_content` text NOT NULL,
  `estimated_asu_content_aa` varchar(255) NOT NULL,
  `export2run` int(11) NOT NULL,
  `pointgroup_choices` text NOT NULL,
  PRIMARY KEY (`sampleNumber`),
  KEY `screenstrategyresults_pipelinestatus_id` (`pipelinestatus_id`),
  CONSTRAINT `screenstrategyresults_ibfk_1` FOREIGN KEY (`pipelinestatus_id`) REFERENCES `pipelinestatus` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=37864 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
