-- PostgreSQL compatible schema
-- translation of mysql schema

-- Table: pipelinestatus
-- This table must be created before dataprocessresults and screenstrategyresults due to foreign key constraints.
CREATE TABLE "pipelinestatus" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "command" VARCHAR(1024) NOT NULL,
  "state" VARCHAR(20) NOT NULL,
  "pipeline" VARCHAR(20) NOT NULL,
  "imagedir" VARCHAR(255) NOT NULL,
  "workdir" VARCHAR(255) NOT NULL,
  "log" TEXT NOT NULL,
  "warning" TEXT NOT NULL,
  "processing_id" INTEGER NOT NULL,
  "hostname" VARCHAR(255) NOT NULL,
  "sampleName" VARCHAR(255) NOT NULL,
  "sampleNumber" INTEGER NOT NULL,
  "username" VARCHAR(30) NOT NULL, -- Increased from 20 to 30 to match Pucks.owner
  "beamline" VARCHAR(255) NOT NULL,
  "starttime" TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  "elapsedtime" VARCHAR(255) NOT NULL,
  "imageSet" VARCHAR(255) NOT NULL,
  "logfile" VARCHAR(1024) NOT NULL,
  "delete" INTEGER NOT NULL,
  "pi_id" INTEGER DEFAULT NULL,
  "esaf_id" INTEGER DEFAULT NULL,
  "primary_group" VARCHAR(30) DEFAULT NULL,
  "datasets" TEXT DEFAULT NULL
);

CREATE INDEX "pipelinestatus_pipeline_idx" ON "pipelinestatus" ("pipeline");
CREATE INDEX "pipelinestatus_username_idx" ON "pipelinestatus" ("username");

-- Table: dataprocessresults
CREATE TABLE "dataprocessresults" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "sampleNumber" INTEGER NOT NULL,
  "sampleName" VARCHAR(255) NOT NULL,
  "imageSet" VARCHAR(255) NOT NULL,
  "state" VARCHAR(255) NOT NULL,
  "software" VARCHAR(255) NOT NULL,
  "scalingsoftware" VARCHAR(255) NOT NULL,
  "collectType" VARCHAR(255) NOT NULL,
  "overlap" INTEGER NOT NULL,
  "inverseOn" INTEGER NOT NULL,
  "firstFrame" VARCHAR(255) NOT NULL,
  "workdir" VARCHAR(255) NOT NULL,
  "subdir" VARCHAR(255) NOT NULL,
  "imagedir" VARCHAR(255) NOT NULL,
  "images" VARCHAR(255) NOT NULL,
  "unitcell" VARCHAR(255) NOT NULL,
  "lowresolution" VARCHAR(255) NOT NULL,
  "lowresolution_inner" VARCHAR(255) NOT NULL,
  "lowresolution_outer" VARCHAR(255) NOT NULL,
  "highresolution" VARCHAR(255) NOT NULL,
  "highresolution_inner" VARCHAR(255) NOT NULL,
  "highresolution_outer" VARCHAR(255) NOT NULL,
  "rmerge" VARCHAR(255) NOT NULL,
  "rmerge_inner" VARCHAR(255) NOT NULL,
  "rmerge_outer" VARCHAR(255) NOT NULL,
  "rpim" VARCHAR(255) NOT NULL,
  "rpim_inner" VARCHAR(255) NOT NULL,
  "rpim_outer" VARCHAR(255) NOT NULL,
  "cchalf" VARCHAR(255) NOT NULL,
  "cchalf_inner" VARCHAR(255) NOT NULL,
  "cchalf_outer" VARCHAR(255) NOT NULL,
  "completeness" VARCHAR(255) NOT NULL,
  "completeness_inner" VARCHAR(255) NOT NULL,
  "completeness_outer" VARCHAR(255) NOT NULL,
  "anom_completeness" VARCHAR(255) NOT NULL,
  "anom_completeness_inner" VARCHAR(255) NOT NULL,
  "anom_completeness_outer" VARCHAR(255) NOT NULL,
  "multiplicity" VARCHAR(255) NOT NULL,
  "multiplicity_inner" VARCHAR(255) NOT NULL,
  "multiplicity_outer" VARCHAR(255) NOT NULL,
  "anom_multiplicity" VARCHAR(255) NOT NULL,
  "anom_multiplicity_inner" VARCHAR(255) NOT NULL,
  "anom_multiplicity_outer" VARCHAR(255) NOT NULL,
  "isigmai" VARCHAR(255) NOT NULL,
  "isigmai_inner" VARCHAR(255) NOT NULL,
  "isigmai_outer" VARCHAR(255) NOT NULL,
  "spacegroup" VARCHAR(255) NOT NULL,
  "truncate_log" VARCHAR(255) NOT NULL,
  "truncate_mtz" VARCHAR(255) NOT NULL,
  "run_stats" TEXT DEFAULT NULL,
  "log" VARCHAR(255) NOT NULL,
  "warning" TEXT NOT NULL,
  "timestamp" TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  "scale_log" VARCHAR(255) NOT NULL,
  "start" VARCHAR(255) NOT NULL,
  "end" VARCHAR(255) NOT NULL,
  "prefix" VARCHAR(255) NOT NULL,
  "isa" VARCHAR(255) NOT NULL,
  "rmeas" VARCHAR(255) NOT NULL,
  "rmeas_inner" VARCHAR(255) NOT NULL,
  "rmeas_outer" VARCHAR(255) NOT NULL,
  "pipeline" VARCHAR(255) NOT NULL,
  "wavelength" VARCHAR(255) NOT NULL,
  "nobs" VARCHAR(255) NOT NULL,
  "nuniq" VARCHAR(255) NOT NULL,
  "table1" TEXT NOT NULL,
  "report_url" VARCHAR(1024) NOT NULL,
  "pipelinestatus_id" INTEGER NOT NULL,
  "reprocess" INTEGER NOT NULL,
  "solve" VARCHAR(255) NOT NULL,
  "spacegroup_choices" TEXT NOT NULL,
  CONSTRAINT "dataprocessresults_pipelinestatus_id_fkey" FOREIGN KEY ("pipelinestatus_id") REFERENCES "pipelinestatus" ("id") ON DELETE CASCADE
);

CREATE INDEX "dataprocessresults_pipelinestatus_id_idx" ON "dataprocessresults" ("pipelinestatus_id");


-- Table: dataset_runs
CREATE TABLE "dataset_runs" (
  "data_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username" VARCHAR(255) DEFAULT NULL,
  "run_prefix" VARCHAR(255) NOT NULL,
  "master_files" TEXT DEFAULT NULL,
  "total_frames" INTEGER DEFAULT NULL,
  "created_at" TIMESTAMP WITHOUT TIME ZONE DEFAULT NULL,
  "collect_type" VARCHAR(255) DEFAULT NULL,
  "headers" TEXT DEFAULT NULL,
  UNIQUE ("run_prefix", "created_at")
);

CREATE INDEX "ix_dataset_runs_run_prefix" ON "dataset_runs" ("run_prefix");


-- Table: screenstrategyresults
CREATE TABLE "screenstrategyresults" (
  "sampleNumber" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "sampleName" VARCHAR(512) NOT NULL,
  "directory" VARCHAR(250) NOT NULL,
  "images" VARCHAR(250) NOT NULL,
  "software" VARCHAR(255) NOT NULL,
  "state" VARCHAR(255) NOT NULL,
  "workdir" VARCHAR(512) NOT NULL,
  "index_table" TEXT NOT NULL,
  "unitcell" VARCHAR(100) NOT NULL,
  "bravais_lattice" VARCHAR(10) NOT NULL,
  "rmsd" VARCHAR(50) NOT NULL,
  "ice_rings" VARCHAR(50) NOT NULL,
  "resolution_from_spots" VARCHAR(30) NOT NULL,
  "n_spots" VARCHAR(30) NOT NULL,
  "n_spots_ice" VARCHAR(30) NOT NULL,
  "n_ice_rings" VARCHAR(30) NOT NULL,
  "avg_spotsize" VARCHAR(20) NOT NULL,
  "spacegroup" VARCHAR(30) NOT NULL,
  "solution_number" VARCHAR(30) NOT NULL,
  "penalty" VARCHAR(30) NOT NULL,
  "mosaicity" VARCHAR(50) NOT NULL,
  "score" VARCHAR(30) NOT NULL,
  "resolution_from_integ" VARCHAR(30) NOT NULL,
  "warning" TEXT NOT NULL,
  "anomalous" SMALLINT NOT NULL,
  "osc_start" VARCHAR(30) NOT NULL,
  "osc_end" VARCHAR(30) NOT NULL,
  "osc_delta" VARCHAR(30) NOT NULL,
  "completeness_native" VARCHAR(30) NOT NULL,
  "completeness_anomalous" VARCHAR(30) NOT NULL,
  "completeness_referencedata" VARCHAR(30) NOT NULL,
  "detectorwarning" VARCHAR(512) NOT NULL,
  "detectordistance" VARCHAR(30) NOT NULL,
  "referencedata" VARCHAR(512) NOT NULL,
  "displaytext" VARCHAR(250) NOT NULL,
  "xplanlog" TEXT NOT NULL,
  "strategy" TEXT NOT NULL,
  "pipelinestatus_id" INTEGER NOT NULL,
  "reprocess" INTEGER NOT NULL,
  "solvent_content" TEXT NOT NULL,
  "estimated_asu_content_aa" VARCHAR(255) NOT NULL,
  "export2run" INTEGER NOT NULL,
  "pointgroup_choices" TEXT NOT NULL,
  CONSTRAINT "screenstrategyresults_pipelinestatus_id_fkey" FOREIGN KEY ("pipelinestatus_id") REFERENCES "pipelinestatus" ("id") ON DELETE CASCADE
);

CREATE INDEX "screenstrategyresults_pipelinestatus_id_idx" ON "screenstrategyresults" ("pipelinestatus_id");