# qp2/image_viewer/plugins/nxds/nxds_merging_worker.py
import os
import shutil
from pathlib import Path

from PyQt5.QtCore import QRunnable, pyqtSignal, QObject

from qp2.pipelines.gmcaproc.symmetry import Symmetry
from qp2.image_viewer.utils.run_job import run_command, is_sbatch_available
from qp2.log.logging_config import get_logger
from qp2.config.programs import ProgramConfig

logger = get_logger(__name__)

NXSCALE_INP_TEMPLATE = """! Generated by QP2 Image Viewer
OUTPUT_FILE=MERGED.HKL
SPACE_GROUP_NUMBER={space_group}
UNIT_CELL_CONSTANTS={unit_cell}
OVERLOAD={saturation_value}
!{sensor_thickness_line}
MAXIMUM_NUMBER_OF_PROCESSORS={nproc}
INCLUDE_RESOLUTION_RANGE= {res_low} {res_high}
POSTREFINE= SKALA B-FACTOR MOSAICITY CELL POSITION

{reference_dataset_section}
{input_files_section}
"""

XDSCONV_INP_TEMPLATE = """! Generated by QP2 Image Viewer
INPUT_FILE=MERGED.HKL
INCLUDE_RESOLUTION_RANGE= {res_low} {res_high}
OUTPUT_FILE=temp.hkl  CCP4
FRIEDEL'S_LAW=TRUE
"""

F2MTZ_SCRIPT_TEMPLATE = """#!/bin/bash
set -e
echo "Running f2mtz..."
f2mtz HKLOUT temp.mtz < F2MTZ.INP
echo "Running cad..."
cad HKLIN1 temp.mtz HKLOUT XDS_ASCII.mtz <<EOF
LABIN FILE 1 ALL
END
echo "Script finished."
"""


class MergingSignals(QObject):
    finished = pyqtSignal(str)
    error = pyqtSignal(str)
    progress = pyqtSignal(str)
    show_lp_file = pyqtSignal(str)  # Signal to show the LP file content


def is_integrate_hkl_valid(file_path: Path) -> bool:
    """Checks if INTEGRATE.HKL ends with '!END_OF_DATA'."""
    if not file_path.exists() or file_path.stat().st_size == 0:
        return False
    try:
        with open(file_path, "rb") as f:
            # Seek to near the end of the file to be efficient
            try:
                f.seek(-1024, os.SEEK_END)
            except OSError:  # file smaller than 1024 bytes
                f.seek(0, os.SEEK_SET)
            last_lines = f.readlines()
            # Decode and strip whitespace from last few lines
            last_lines_str = [
                line.decode("utf-8", errors="ignore").strip() for line in last_lines
            ]
            
            if "!END_OF_DATA" not in last_lines_str:
                return False

            # Check for at least 5 lines not starting with "!" (data lines)
            f.seek(0)
            data_lines_count = 0
            for line in f:
                decoded_line = line.decode("utf-8", errors="ignore").strip()
                if decoded_line and not decoded_line.startswith('!'):
                    data_lines_count += 1
                if data_lines_count >= 5:
                    return True
            
            return False

    except Exception as e:
        logger.warning(f"Could not validate {file_path}: {e}")
        return False


class NXDSMergingWorker(QRunnable):
    def __init__(self, dataset_paths, redis_conn, settings: dict):
        super().__init__()
        self.dataset_paths = dataset_paths
        self.redis_conn = redis_conn
        self.settings = settings
        self.signals = MergingSignals()

    def run(self):
        merge_dir = None
        try:
            hkl_files = []
            for master_file in self.dataset_paths:
                redis_key = f"analysis:out:nxds:{master_file}"
                proc_dir_str = self.redis_conn.hget(redis_key, "_proc_dir")
                if proc_dir_str:
                    integrate_hkl = Path(proc_dir_str) / "INTEGRATE.HKL"
                    if is_integrate_hkl_valid(integrate_hkl):
                        hkl_files.append(integrate_hkl)
                    elif integrate_hkl.exists():
                        logger.warning(
                            f"Skipping malformed file (missing !END_OF_DATA): {integrate_hkl}"
                        )

            if not hkl_files:
                raise FileNotFoundError(
                    "No valid INTEGRATE.HKL files found for the selected datasets."
                )

            # 1. Determine the common prefix from the dataset names.
            if not self.dataset_paths:
                raise ValueError(
                    "No dataset paths provided to determine a common prefix."
                )

            # Get basenames without the standard master file suffix
            basenames = [
                os.path.basename(p)
                .replace("_master.h5", "")
                .replace("_master.hdf5", "")
                for p in self.dataset_paths
            ]

            common_prefix = os.path.commonprefix(basenames).rstrip("_-")
            if not common_prefix:  # Fallback if names are completely different
                common_prefix = "merged_results"

            # 2. Construct the new directory name with the descriptive tag.
            num_datasets = len(hkl_files)
            dir_tag = f"merge_solve_{common_prefix}_{num_datasets}datasets"

            # 3. Determine the base directory (one level up from the dataset proc dir).
            #    This places the new directory as a sibling, not a child.
            base_dir = Path(hkl_files[0]).parent.parent

            # 4. Create the final merge directory path.
            merge_dir = base_dir / dir_tag

            merge_dir.mkdir(exist_ok=True)

            # --- Step 1: Run nXSCALE ---
            self.signals.progress.emit("Running nXSCALE...")
            self._run_nxscale(hkl_files, merge_dir)

            # Show LP file content after nxscale finishes
            lp_file = merge_dir / "nXSCALE.LP"
            if lp_file.exists():
                self.signals.show_lp_file.emit(lp_file.read_text())

            # --- Step 2: Run XDSCONV ---
            self.signals.progress.emit("Running XDSCONV...")
            self._run_xdsconv(merge_dir)

            # --- Step 3: Run F2MTZ and CAD ---
            self.signals.progress.emit("Converting to MTZ...")
            self._run_mtz_conversion(merge_dir)

            # --- Step 4: Run Dimple if PDB is provided ---
            final_message = (
                f"Merge and MTZ conversion complete. Results are in:\n{merge_dir}"
            )
            if self.settings.get("pdb_file"):
                self.signals.progress.emit("Running Dimple for structure solution...")
                final_message = self._run_dimple(merge_dir)
                # --- Step 5: Launch Coot ---
                self.signals.progress.emit("Launching Coot...")
                self._launch_coot(merge_dir)

            self.signals.finished.emit(final_message)

        except Exception as e:
            logger.error(f"nXDS processing pipeline failed: {e}", exc_info=True)
            error_message = f"Error during processing pipeline: {e}"
            if merge_dir:
                error_message += f"\nCheck logs in: {merge_dir}"
            self.signals.error.emit(error_message)

    def _run_nxscale(self, hkl_files, merge_dir):
        logger.info("Step 1: Running nXSCALE...")
        reference_dataset_section = ""
        ref_hkl = self.settings.get("reference_hkl")
        if ref_hkl and Path(ref_hkl).exists():
            reference_dataset_section = f"REFERENCE_DATA_SET={ref_hkl}\n"

        input_files_section = "\n".join([f"INPUT_FILE={path}" for path in hkl_files])
        spg_number = Symmetry.symbol_to_number(self.settings["space_group"])
        
        sensor_thickness = self.settings.get("sensor_thickness")
        sensor_thickness_line = ""
        if sensor_thickness is not None and sensor_thickness > 0:
             sensor_thickness_line = f"!SENSOR_THICKNESS={sensor_thickness:.4f}"
        
        inp_content = NXSCALE_INP_TEMPLATE.format(
            space_group=spg_number,
            unit_cell=self.settings["unit_cell"],
            saturation_value=self.settings["saturation_value"],
            sensor_thickness_line=sensor_thickness_line,
            nproc=self.settings["nproc"],
            res_low=self.settings["res_low"],
            res_high=self.settings["res_high"],
            reference_dataset_section=reference_dataset_section,
            input_files_section=input_files_section,
        )
        inp_path = merge_dir / "nXSCALE.INP"
        with open(inp_path, "w") as f:
            f.write(inp_content)

        run_command(
            cmd=["nxscale_par"],
            pre_command=ProgramConfig.get_setup_command('nxds'),
            cwd=str(merge_dir),
            method="slurm" if is_sbatch_available() else "shell",
            job_name="nxscale_merge",
            background=False,
            processors=self.settings.get("nproc", 24),
            walltime="02:00:00",
            memory="64gb",
        )
        if not (merge_dir / "MERGED.HKL").exists():
            raise FileNotFoundError("nxscale_par did not produce MERGED.HKL.")

    def _run_xdsconv(self, merge_dir):
        logger.info("Step 2: Running XDSCONV...")
        inp_content = XDSCONV_INP_TEMPLATE.format(
            res_low=self.settings["res_low"], res_high=self.settings["res_high"]
        )
        inp_path = merge_dir / "XDSCONV.INP"
        with open(inp_path, "w") as f:
            f.write(inp_content)

        run_command(
            cmd=["xdsconv"],
            pre_command=ProgramConfig.get_setup_command('nxds'),
            cwd=str(merge_dir),
            method="shell",  # This is fast, no need for slurm
            job_name="xdsconv_run",
            background=False,
        )
        if not (merge_dir / "F2MTZ.INP").exists():
            raise FileNotFoundError("xdsconv did not produce F2MTZ.INP.")

    def _run_mtz_conversion(self, merge_dir):
        logger.info("Step 3: Running F2MTZ and CAD...")
        script_path = merge_dir / "f2mtz.sh"
        with open(script_path, "w") as f:
            f.write(F2MTZ_SCRIPT_TEMPLATE)
        script_path.chmod(0o755)

        run_command(
            cmd=[str(script_path)],
            pre_command=ProgramConfig.get_setup_command('nxds'),
            cwd=str(merge_dir),
            method="shell",
            job_name="f2mtz_cad_run",
            background=False,
        )
        if not (merge_dir / "XDS_ASCII.mtz").exists():
            raise FileNotFoundError(
                "MTZ conversion script did not produce XDS_ASCII.mtz."
            )

    def _run_dimple(self, merge_dir) -> str:
        logger.info("Step 4: Running Dimple...")
        pdb_file = Path(self.settings["pdb_file"])
        if not pdb_file.exists():
            raise FileNotFoundError(f"PDB file for Dimple not found: {pdb_file}")

        # Copy PDB file to merge dir to keep run self-contained
        shutil.copy(pdb_file, merge_dir / pdb_file.name)

        run_command(
            cmd=["dimple", "XDS_ASCII.mtz", pdb_file.name, "dimple"],
            pre_command=ProgramConfig.get_setup_command('ccp4'),
            cwd=str(merge_dir),
            method="slurm" if is_sbatch_available() else "shell",
            job_name="dimple_solve",
            background=False,
            processors=1,
            walltime="01:00:00",
            memory="2gb",
        )

        # Check for a successful dimple run indicator
        if not (merge_dir / "dimple" / "final.pdb").exists():
            logger.warning("Dimple finished, but final.pdb was not found.")
            return f"Dimple run completed with warnings. Check results in:\n{merge_dir}"

        return f"Dimple structure solution successful!\nResults are in:\n{merge_dir / 'dimple'}"

    def _launch_coot(self, merge_dir):
        logger.info("Step 5: Checking for files and launching Coot...")
        dimple_dir = merge_dir / "dimple"
        final_pdb = dimple_dir / "final.pdb"
        final_mtz = dimple_dir / "final.mtz"

        if final_pdb.exists() and final_mtz.exists():
            logger.info(f"Found files, launching Coot for {final_pdb} and {final_mtz}")
            run_command(
                cmd=["coot", "--pdb", str(final_pdb), "--auto", str(final_mtz)],
                pre_command=ProgramConfig.get_setup_command('ccp4'),
                cwd=str(dimple_dir),
                method="shell",
                job_name="coot_launcher",
                background=True,  # Launch and detach
            )
        else:
            logger.warning(
                "Could not find final.pdb and/or final.mtz. Skipping Coot launch."
            )
