# qp2/image_viewer/plugins/crystfel/crystfel_geometry.py
import argparse
import os
import sys
from typing import Optional, Tuple

import h5py
import numpy as np
import redis

PANEL_NAME = "p0"

try:
    from qp2.xio.hdf5_manager import HDF5Reader
    from qp2.image_viewer.utils.mask_computation import compute_detector_mask
    from qp2.image_viewer.config import MASKED_CIRCLES, MASKED_RECTANGLES
    from qp2.log.logging_config import get_logger, setup_logging
    from qp2.image_viewer.utils.redis_cache import save_numpy_array_to_redis

except ImportError:
    # This allows the script to provide a helpful error if qp2 is not in the python path
    print(
        "ERROR: Could not import qp2 modules. Make sure the project root is in your PYTHONPATH."
    )
    HDF5Reader = None  # Set to None to handle errors gracefully

if HDF5Reader is not None:
    logger = get_logger(__name__)

# --- CrystFEL Geometry Template ---
GEOMETRY_TEMPLATE = """
; CrystFEL geometry file generated by QP2 Image Viewer
;
; Master File: {master_file}
;
;---------------------------------------------------
; photon energy and clen are required for indexing
;---------------------------------------------------
photon_energy = {energy} ; eV
clen = {distance} ; metres
adu_per_photon = 1.0
coffset = 0.
;---------------------------------------------------
; detector geometry
;---------------------------------------------------
res = {resolution} ; pixels/metre
; The data path inside the HDF5 file (Cheetah-style)
data = /entry/data/data
dim0 = %
dim1 = ss
dim2 = fs

flag_morethan = {saturation_value}


; Panel definition (single panel for Eiger/Pilatus)
{PANEL_NAME}/min_fs = 0
{PANEL_NAME}/max_fs = {nx}
{PANEL_NAME}/min_ss = 0
{PANEL_NAME}/max_ss = {ny}
{PANEL_NAME}/corner_x = -{xbeam}
{PANEL_NAME}/corner_y = -{ybeam}
{PANEL_NAME}/fs = x
{PANEL_NAME}/ss = y
"""

MASK_TEMPLATE = """
;---------------------------------------------------
; External bad pixel mask
;---------------------------------------------------
; This tells CrystFEL to load a separate file containing bad pixel information.
;
; Path to the HDF5 file containing the mask array.
{PANEL_NAME}/mask_file = {mask_file_path}
{PANEL_NAME}/mask = /data/data
{PANEL_NAME}/mask_good = 0x0
{PANEL_NAME}/mask_bad = 0x1

"""


# --- END NEW TEMPLATE ---


def _generate_bad_regions_from_mask(mask: np.ndarray) -> str:
    """
    Finds contiguous horizontal and vertical gaps in a boolean mask
    and formats them for a CrystFEL geometry file.
    """
    if mask is None:
        return ""

    h, w = mask.shape

    # Find vertical gaps (columns that are all masked)
    vertical_gap_indices = np.where(np.all(mask, axis=0))[0]
    v_gaps = _get_contiguous_ranges(vertical_gap_indices)

    # Find horizontal gaps (rows that are all masked)
    horizontal_gap_indices = np.where(np.all(mask, axis=1))[0]
    h_gaps = _get_contiguous_ranges(horizontal_gap_indices)

    blocks = []
    # Format vertical gaps
    for i, (start, end) in enumerate(v_gaps):
        blocks.append(f"bad_v{i + 1}/min_fs = {start}")
        blocks.append(f"bad_v{i + 1}/min_ss = 0")
        blocks.append(f"bad_v{i + 1}/max_fs = {end}")
        blocks.append(f"bad_v{i + 1}/max_ss = {h - 1}")

    # Format horizontal gaps
    for i, (start, end) in enumerate(h_gaps):
        blocks.append(f"bad_h{i + 1}/min_fs = 0")
        blocks.append(f"bad_h{i + 1}/min_ss = {start}")
        blocks.append(f"bad_h{i + 1}/max_fs = {w - 1}")
        blocks.append(f"bad_h{i + 1}/max_ss = {end}")

    return "\n".join(blocks)


def _get_contiguous_ranges(indices: np.ndarray) -> list:
    """Finds contiguous blocks of numbers in a sorted array of indices."""
    if indices.size == 0:
        return []

    ranges = []
    start = indices[0]
    for i in range(1, indices.size):
        if indices[i] != indices[i - 1] + 1:
            # End of a block
            ranges.append((start, indices[i - 1]))
            start = indices[i]
    # Add the last block
    ranges.append((start, indices[-1]))
    return ranges


def generate_crystfel_geometry_file(
    master_file_path: str,
    output_geom_path: Optional[str] = None,
    bad_pixels_file_path: Optional[str] = None,
    include_gaps: bool = False,
    include_mask: bool = False,
    save_mask_to_redis: bool = False,
    redis_host: Optional[str] = None,
    redis_port: int = 6379,
) -> Tuple[str, Optional[str]]:
    """
    Generates a CrystFEL geometry file (.geom) from an HDF5 master file.

    This function contains the core logic and can be called from other modules.

    Args:
        master_file_path: Absolute path to the input HDF5 master file.
        output_geom_path: Path for the output .geom file. If None, a default
                          path next to the master file is used.
        bad_pixels_file_path: Path for the output .h5 file containing the bad
                              pixel mask. If None, no mask will be generated.
        include_gaps: If True, calculates and includes bad regions for panel gaps.
        include_mask: If True, includes the external mask file reference in the geometry file.


    Returns:
        The absolute path to the generated .geom file, and key to saved pixelmap in redis

    Raises:
        ValueError: If the master file cannot be read or contains no data.
        IOError: If files cannot be written.
        Exception: For other processing errors.
    """
    if not HDF5Reader:
        raise ImportError("qp2 modules are not available. Cannot generate geometry.")

    logger.info(f"Generating CrystFEL geometry for: {master_file_path}")
    redis_conn = None

    if save_mask_to_redis and redis_host:
        try:
            redis_conn = redis.Redis(host=redis_host, port=redis_port)
            redis_conn.ping()
            logger.info(f"Successfully connected to Redis at {redis_host}:{redis_port}")
        except redis.RedisError as e:
            logger.error(f"Could not connect to Redis: {e}. Mask will not be saved.")
            redis_conn = None

    # 1. Determine output path
    if output_geom_path:
        final_output_path = os.path.abspath(output_geom_path)
    else:
        base_dir = os.path.dirname(master_file_path)
        base_name = os.path.splitext(os.path.basename(master_file_path))[0]
        final_output_path = os.path.join(base_dir, f"{base_name}.geom")

    # 2. Use HDF5Reader to get necessary info
    reader = HDF5Reader(master_file_path, start_timer=False)
    params = reader.get_parameters()
    sample_image = reader.get_frame(0)
    reader.close()

    if sample_image is None:
        raise ValueError(
            f"Could not read a sample frame from the master file: {master_file_path}"
        )

    # 3. Compute the full detector mask
    bit_depth = params.get("nbits", 32)
    mask_value = (2**bit_depth) - 1
    detector_mask, _ = compute_detector_mask(
        image=sample_image,
        params=params,
        mask_values={mask_value, -1},
        masked_circles=MASKED_CIRCLES,
        masked_rectangles=MASKED_RECTANGLES,
    )

    # 4. Generate the base geometry text
    energy_ev = 12398.42 / params["wavelength"]
    distance_m = params["det_dist"] / 1000.0
    pixel_size_m = params["pixel_size"] / 1000.0
    resolution_px_per_m = 1.0 / pixel_size_m
    saturation = params.get("saturation_value", 2**20)

    geom_params = {
        "master_file": os.path.basename(master_file_path),
        "energy": f"{energy_ev:.2f}",
        "distance": f"{distance_m:.6f}",
        "resolution": f"{resolution_px_per_m:.1f}",
        "nx": params["nx"] - 1,
        "ny": params["ny"] - 1,
        "xbeam": params["beam_x"],
        "ybeam": params["beam_y"],
        "saturation_value": int(saturation),
        "PANEL_NAME": "p0",
    }

    final_geom_text = GEOMETRY_TEMPLATE.format(**geom_params)

    # 5. Conditionally add the requested blocks
    if include_gaps:
        logger.info("Including panel gap information in geometry file.")
        masked_regions_text = _generate_bad_regions_from_mask(detector_mask)
        final_geom_text += f"\n{masked_regions_text}"

    mask_redis_key = None  # Initialize

    if save_mask_to_redis and redis_conn:
        # Save the mask to Redis instead of a file
        logger.info("Saving computed bad pixel mask to Redis cache...")
        detector_name = params.get("detector", "unknown_detector").replace(" ", "_")
        mask_shape = f"{detector_mask.shape[0]}x{detector_mask.shape[1]}"
        # Create a unique, descriptive key
        mask_redis_key = f"{detector_name}:{mask_shape}"

        success = save_numpy_array_to_redis(
            redis_host, redis_port, mask_redis_key, detector_mask
        )
        if success:
            logger.info(
                f"Mask saved. Downstream workers should load from Redis key: '{mask_redis_key}'"
            )
            if not success:
                mask_redis_key = None
        else:
            logger.error("Failed to save mask to Redis. No mask will be referenced.")

    if bad_pixels_file_path is not None:
        final_badpixel_path = os.path.abspath(bad_pixels_file_path)

        logger.info("Creating an external bad pixel map.")

        with h5py.File(final_badpixel_path, "w") as hf:
            mask_for_crystfel = detector_mask.astype(np.int8)
            hf.create_dataset("/data/data", data=mask_for_crystfel, compression="gzip")
        logger.info(f"Wrote bad pixel map to: {final_badpixel_path}")

        if include_mask:
            logger.info("Linking external bad pixel map in geometry file.")
            mask_block_text = MASK_TEMPLATE.format(
                mask_file_path=os.path.abspath(final_badpixel_path), PANEL_NAME=PANEL_NAME
            )
            final_geom_text += f"\n{mask_block_text}"

    # 6. Write the final file
    with open(final_output_path, "w") as f:
        f.write(final_geom_text)

    logger.info(f"Successfully generated geometry file: {final_output_path}")
    return final_output_path, mask_redis_key


def main():
    """
    Main function to run the geometry generation from the command line.
    This function now primarily handles argument parsing and calls the core function.
    """
    # 1. Configure logging and the argument parser
    setup_logging(root_name="qp2", log_level="INFO")

    parser = argparse.ArgumentParser(
        description="Generate a CrystFEL geometry file (.geom) and/or a bad pixel map (.h5) from an HDF5 master file.",
        formatter_class=argparse.RawTextHelpFormatter,
    )
    parser.add_argument(
        "master_file", type=str, help="Path to the input HDF5 master file."
    )

    parser.add_argument(
        "--include_gaps",
        action="store_true",
        help="Include masked panel gaps (bad_v*/bad_h*) in the geometry file.",
    )
    parser.add_argument(
        "--include_mask",
        action="store_true",
        help="Include the bad pixel mask section in the geometry file. Default is False.",
    )
    parser.add_argument(
        "--pixel_map",
        "--pixelmap",
        type=str,
        default=None,
        help="output bad pixel map path.",
    )

    parser.add_argument(
        "--geometry_file",
        "--geom_file",
        "-g",
        type=str,
        default=None,
        help="output geometry file",
    )

    parser.add_argument(
        "--save_mask_to_redis",
        action="store_true",
        help="Save the computed bad pixel map to a Redis key instead of an HDF5 file.",
    )
    parser.add_argument(
        "--redis_host",
        type=str,
        default=None,
        help="Redis server host for saving the mask.",
    )
    parser.add_argument(
        "--redis_port", type=int, default=6379, help="Redis server port."
    )

    args = parser.parse_args()

    try:
        # 2. Call the core function with the parsed arguments
        generate_crystfel_geometry_file(
            master_file_path=args.master_file,
            output_geom_path=args.geometry_file,
            bad_pixels_file_path=args.pixel_map,
            include_gaps=args.include_gaps,
            include_mask=args.include_mask,
            save_mask_to_redis=args.save_mask_to_redis,
            redis_host=args.redis_host,
            redis_port=args.redis_port,
        )
    except Exception as e:
        # The core function will log the detailed traceback.
        # We just need to log a high-level failure message and exit.
        logger.critical(f"Geometry generation failed. Error: {e}")
        sys.exit(1)


if __name__ == "__main__":
    main()
