-- PostgreSQL compatible schema with reduced NOT NULL constraints for flexibility

DROP TABLE IF EXISTS "screenstrategyresults";
DROP TABLE IF EXISTS "dataprocessresults";
DROP TABLE IF EXISTS "pipelinestatus";
DROP TABLE IF EXISTS "dataset_runs";

-- Table: pipelinestatus
-- This table defines a pipeline run and its core identifiers.
CREATE TABLE "pipelinestatus" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "command" VARCHAR(1024) DEFAULT NULL,
  "state" VARCHAR(20) NOT NULL, -- ESSENTIAL: A pipeline always has a state.
  "pipeline" VARCHAR(20) NOT NULL, -- ESSENTIAL: Identifies the type of pipeline.
  "imagedir" VARCHAR(255) NOT NULL, -- ESSENTIAL: Location of the source data.
  "workdir" VARCHAR(255) NOT NULL, -- ESSENTIAL: Location of the processing files.
  "log" TEXT DEFAULT NULL,
  "warning" TEXT DEFAULT NULL,
  "processing_id" INTEGER DEFAULT 0,
  "hostname" VARCHAR(255) NOT NULL,
  "sampleName" VARCHAR(255) NOT NULL, -- ESSENTIAL: The name of the sample being processed.
  "sampleNumber" INTEGER DEFAULT 0,
  "username" VARCHAR(30) NOT NULL,
  "beamline" VARCHAR(255) DEFAULT NULL,

  -- starttime is set by the DB on creation, so it should be NOT NULL.
  "starttime" TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
  "elapsedtime" VARCHAR(255) DEFAULT '0s',
  "imageSet" VARCHAR(255) DEFAULT 'All',
  "logfile" VARCHAR(1024) DEFAULT NULL,
  "delete" INTEGER DEFAULT 0,
  "pi_id" INTEGER DEFAULT NULL,
  "esaf_id" INTEGER DEFAULT NULL,
  "primary_group" VARCHAR(30) DEFAULT NULL,
  "datasets" TEXT DEFAULT NULL
);

CREATE INDEX "pipelinestatus_pipeline_idx" ON "pipelinestatus" ("pipeline");
CREATE INDEX "pipelinestatus_username_idx" ON "pipelinestatus" ("username");


-- Table: dataprocessresults
-- Contains results from data processing. Most fields are optional as they are
-- populated only upon successful completion of various pipeline stages.
CREATE TABLE "dataprocessresults" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "sampleNumber" INTEGER DEFAULT 0,
  "sampleName" VARCHAR(255) NOT NULL, -- ESSENTIAL: Links results back to a sample.
  "imageSet" VARCHAR(255) DEFAULT NULL,
  "state" VARCHAR(255) DEFAULT 'PENDING',
  "software" VARCHAR(255) DEFAULT NULL,
  "scalingsoftware" VARCHAR(255) DEFAULT NULL,
  "collectType" VARCHAR(255) DEFAULT NULL,
  "overlap" INTEGER DEFAULT 0,
  "inverseOn" INTEGER DEFAULT 0,
  "firstFrame" VARCHAR(255) DEFAULT NULL,
  "workdir" VARCHAR(255) DEFAULT NULL,
  "subdir" VARCHAR(255) DEFAULT NULL,
  "imagedir" VARCHAR(255) DEFAULT NULL,
  "images" VARCHAR(255) DEFAULT NULL,
  "unitcell" VARCHAR(255) DEFAULT NULL,
  "lowresolution" VARCHAR(255) DEFAULT NULL,
  "lowresolution_inner" VARCHAR(255) DEFAULT NULL,
  "lowresolution_outer" VARCHAR(255) DEFAULT NULL,
  "highresolution" VARCHAR(255) DEFAULT NULL,
  "highresolution_inner" VARCHAR(255) DEFAULT NULL,
  "highresolution_outer" VARCHAR(255) DEFAULT NULL,
  "rmerge" VARCHAR(255) DEFAULT NULL,
  "rmerge_inner" VARCHAR(255) DEFAULT NULL,
  "rmerge_outer" VARCHAR(255) DEFAULT NULL,
  "rpim" VARCHAR(255) DEFAULT NULL,
  "rpim_inner" VARCHAR(255) DEFAULT NULL,
  "rpim_outer" VARCHAR(255) DEFAULT NULL,
  "cchalf" VARCHAR(255) DEFAULT NULL,
  "cchalf_inner" VARCHAR(255) DEFAULT NULL,
  "cchalf_outer" VARCHAR(255) DEFAULT NULL,
  "completeness" VARCHAR(255) DEFAULT NULL,
  "completeness_inner" VARCHAR(255) DEFAULT NULL,
  "completeness_outer" VARCHAR(255) DEFAULT NULL,
  "anom_completeness" VARCHAR(255) DEFAULT NULL,
  "anom_completeness_inner" VARCHAR(255) DEFAULT NULL,
  "anom_completeness_outer" VARCHAR(255) DEFAULT NULL,
  "multiplicity" VARCHAR(255) DEFAULT NULL,
  "multiplicity_inner" VARCHAR(255) DEFAULT NULL,
  "multiplicity_outer" VARCHAR(255) DEFAULT NULL,
  "anom_multiplicity" VARCHAR(255) DEFAULT NULL,
  "anom_multiplicity_inner" VARCHAR(255) DEFAULT NULL,
  "anom_multiplicity_outer" VARCHAR(255) DEFAULT NULL,
  "isigmai" VARCHAR(255) DEFAULT NULL,
  "isigmai_inner" VARCHAR(255) DEFAULT NULL,
  "isigmai_outer" VARCHAR(255) DEFAULT NULL,
  "spacegroup" VARCHAR(255) DEFAULT NULL,
  "truncate_log" VARCHAR(255) DEFAULT NULL,
  "truncate_mtz" VARCHAR(255) DEFAULT NULL,
  "run_stats" TEXT DEFAULT NULL,
  "log" VARCHAR(255) DEFAULT NULL,
  "warning" TEXT DEFAULT NULL,
  "timestamp" TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
  "scale_log" VARCHAR(255) DEFAULT NULL,
  "start" VARCHAR(255) DEFAULT NULL,
  "end" VARCHAR(255) DEFAULT NULL,
  "prefix" VARCHAR(255) DEFAULT NULL,
  "isa" VARCHAR(255) DEFAULT NULL,
  "rmeas" VARCHAR(255) DEFAULT NULL,
  "rmeas_inner" VARCHAR(255) DEFAULT NULL,
  "rmeas_outer" VARCHAR(255) DEFAULT NULL,
  "pipeline" VARCHAR(255) DEFAULT NULL,
  "wavelength" VARCHAR(255) DEFAULT NULL,
  "nobs" VARCHAR(255) DEFAULT NULL,
  "nuniq" VARCHAR(255) DEFAULT NULL,
  "table1" TEXT DEFAULT NULL,
  "report_url" VARCHAR(1024) DEFAULT NULL,
  "pipelinestatus_id" INTEGER NOT NULL, -- ESSENTIAL: This links the results to a specific run.
  "reprocess" INTEGER DEFAULT 0,
  "solve" VARCHAR(255) DEFAULT NULL,
  "spacegroup_choices" TEXT DEFAULT NULL,
  CONSTRAINT "dataprocessresults_pipelinestatus_id_fkey" FOREIGN KEY ("pipelinestatus_id") REFERENCES "pipelinestatus" ("id") ON DELETE CASCADE
);

CREATE INDEX "dataprocessresults_pipelinestatus_id_idx" ON "dataprocessresults" ("pipelinestatus_id");


-- Table: dataset_runs
CREATE TABLE "dataset_runs" (
  "data_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username" VARCHAR(255) DEFAULT NULL,
  "run_prefix" VARCHAR(255) NOT NULL, -- ESSENTIAL: Part of a unique identifier for a run.
  "master_files" TEXT DEFAULT NULL,
  "total_frames" INTEGER DEFAULT NULL,
  "created_at" TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
  "collect_type" VARCHAR(255) DEFAULT NULL,
  "headers" TEXT DEFAULT NULL,
  UNIQUE ("run_prefix", "created_at")
);

CREATE INDEX "ix_dataset_runs_run_prefix" ON "dataset_runs" ("run_prefix");


-- Table: screenstrategyresults
-- Contains results from strategy runs. Most are optional as they are populated
-- only upon successful completion of various strategy stages.
CREATE TABLE "screenstrategyresults" (
  "sampleNumber" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "sampleName" VARCHAR(512) DEFAULT NULL,
  "directory" VARCHAR(250) DEFAULT NULL,
  "images" VARCHAR(250) DEFAULT NULL,
  "software" VARCHAR(255) DEFAULT NULL,
  "state" VARCHAR(255) DEFAULT 'PENDING',
  "workdir" VARCHAR(512) DEFAULT NULL,
  "index_table" TEXT DEFAULT NULL,
  "unitcell" VARCHAR(100) DEFAULT NULL,
  "bravais_lattice" VARCHAR(10) DEFAULT NULL,
  "rmsd" VARCHAR(50) DEFAULT NULL,
  "ice_rings" VARCHAR(50) DEFAULT NULL,
  "resolution_from_spots" VARCHAR(30) DEFAULT NULL,
  "n_spots" VARCHAR(30) DEFAULT NULL,
  "n_spots_ice" VARCHAR(30) DEFAULT NULL,
  "n_ice_rings" VARCHAR(30) DEFAULT NULL,
  "avg_spotsize" VARCHAR(20) DEFAULT NULL,
  "spacegroup" VARCHAR(30) DEFAULT NULL,
  "solution_number" VARCHAR(30) DEFAULT NULL,
  "penalty" VARCHAR(30) DEFAULT NULL,
  "mosaicity" VARCHAR(50) DEFAULT NULL,
  "score" VARCHAR(30) DEFAULT NULL,
  "resolution_from_integ" VARCHAR(30) DEFAULT NULL,
  "warning" TEXT DEFAULT NULL,
  "anomalous" SMALLINT DEFAULT 0,
  "osc_start" VARCHAR(30) DEFAULT NULL,
  "osc_end" VARCHAR(30) DEFAULT NULL,
  "osc_delta" VARCHAR(30) DEFAULT NULL,
  "completeness_native" VARCHAR(30) DEFAULT NULL,
  "completeness_anomalous" VARCHAR(30) DEFAULT NULL,
  "completeness_referencedata" VARCHAR(30) DEFAULT NULL,
  "detectorwarning" VARCHAR(512) DEFAULT NULL,
  "detectordistance" VARCHAR(30) DEFAULT NULL,
  "referencedata" VARCHAR(512) DEFAULT NULL,
  "displaytext" VARCHAR(250) DEFAULT NULL,
  "xplanlog" TEXT DEFAULT NULL,
  "strategy" TEXT DEFAULT NULL,
  "pipelinestatus_id" INTEGER NOT NULL, -- ESSENTIAL: This links the strategy results to a specific run.
  "reprocess" INTEGER DEFAULT 0,
  "solvent_content" TEXT DEFAULT NULL,
  "estimated_asu_content_aa" VARCHAR(255) DEFAULT NULL,
  "export2run" INTEGER DEFAULT 0,
  "pointgroup_choices" TEXT DEFAULT NULL,
  CONSTRAINT "screenstrategyresults_pipelinestatus_id_fkey" FOREIGN KEY ("pipelinestatus_id") REFERENCES "pipelinestatus" ("id") ON DELETE CASCADE
);

CREATE INDEX "screenstrategyresults_pipelinestatus_id_idx" ON "screenstrategyresults" ("pipelinestatus_id");